version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "localstack-bug"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-83da3a40"
s3_prefix = "localstack-bug"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
